### ISSUE TITLE
remove who we are section

### ISSUE THREAD

**Issue by Iconians** [waytohealthfoundation/release-2024#15]
remove the whoArewe section and place the SVG in svgData.js, see enclosed picture showing the section to be removed

![Image](https://github.com/waytohealthfoundation/release-2024/assets/95727830/f511e46d-855e-46c6-a3c2-2aa0e7d98932)

**Comment by Rahnken** [comment]
Why do you want to save that image data in a separate js file? That SVG is already inside the assets folder

**Comment by waytohealthfoundation** [comment]
@Rahnken when you moved the carousel out, we noticed you had an empty svg file in the PR. we thought you were anticipating moving the svg from the index.html out as well.

**Comment by Rahnken** [comment]
I can save that data, the only differences between that svg data and the `Way_to_Health_color_logo_icons_only.svg` is a few styling things, and the viewBox sizing. the actual svg images are identical I did move some file references for the assets/corousel to have access to them in the js , maybe I made an svg file by accident with that but I don't think that svg data needs to be saved in this instance

**Comment by Iconians** [comment]
ok if we have it where it's available in case we still need it later I don't see an issue in removing the one in the section along with the rest of that section
