### ISSUE TITLE
move missionTrips section to ourwork.html

### ISSUE THREAD

**Issue by Iconians** [waytohealthfoundation/release-2024#20]
move missionTrips section to ourwork.html for now as that is a section in that page

**Comment by Rahnken** [comment]
I was reading through the site , and trying to make sure I understand what is suppose to be moving, and what needs to be still on the index page. 

When you say Mission Trips Section, is that suppose to include the scripture , how to help sections ( those with a class of how-to-help__xxx) or just the code inside of the section with an id of MissionTrips, currently on ln 90 - ln 107

**Comment by Iconians** [comment]
it's the code only inside that section so lines 90-107, Thank you for clarifying, I'll try to write clearer issues
