### ISSUE TITLE
WHO WE ARE (on the aboutPage)

### ISSUE THREAD

**Issue by Iconians** [waytohealthfoundation/release-2024#31]
WHO WE ARE 

Vision: TBD
 
Values: TBD
 
Statement of Faith: 1. We believe the Bible to be the inspired, authoritative Word of God, useful to teach us truth about God and his love, and to correct us when we are wrong. God uses Scripture to prepare and equip his people to do every good work.2. We believe in one God, eternally existent in three persons: Father, Son, and Holy Spirit.3. We believe that Jesus is the Christ, the Anoited Son of God, fully human and fully divine. He was born of a virgin, performed miracles, and lived a sinless life. His death on the cross provided the atoning sacrifice for the sinds of the world. We believe in his bodily resurrection, his ascension to heaven and that he will return again at the time appointed by the Father.4. We believe that all humans are created in God's image but all have sinned and are therefore under God's judgment. We believe that faith in God's Son, Jesus, is the only path to salvation, to escape God's judgment.

**Comment by waytohealthfoundation** [comment]
Line 4 correct Hod to God.
In the entire piece capitalize the H in He and Him’s please.
Thank you Clayton, beautiful work. I am looking forward to seeing the finished product!  Merry Christmas
Lisa

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Clayton Cripe ***@***.***>
Sent: Saturday, December 23, 2023 8:16:46 PM
To: waytohealthfoundation/release-2024 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [waytohealthfoundation/release-2024] WHO WE ARE (on the aboutPage) (Issue #31)


WHO WE ARE

Vision: TBD

Values: TBD

Statement of Faith: 1. We believe the Bible to be the inspired, authoritative Word of God, useful to teach us truth about God and his love, and to correct us when we are wrong. Hod uses Scripture to prepare and equip his people to do every good work.2. We believe in one God, eternally existent in three persons: Father, Son, and Holy Spirit.3. We believe that Jesus is the Christ, the Anoited Son of God, fully human and fully divine. He was born of a virgin, performed miracles, and lived a sinless life. His death on the cross provided the atoning sacrifice for the sinds of the world. We believe in his bodily resurrection, his ascension to heaven and that he will return again at the time appointed by the Father.4. We believe that all humans are created in God's image but all have sinned and are therefore under God's judgment. We believe that faith in God's Son, Jesus, is the only path to salvation, to escape God's judgment.

**Comment by Deppravacion** [comment]
lisa is getting a picture of what it looks like when the sausage is made hehehe

**Comment by waytohealthfoundation** [comment]
Lots of detailed tedious work. 🙏🏻🙏🏻🙏🏻

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Rahnken** [comment]
@waytohealthfoundation  @Iconians 
Just checking a couple things in the copy 

``` We believe in his bodily resurrection, his ascension to heaven and that he will return again at the time appointed by the Father.``` 

What his/he should be capitalized if any? from context I believe they should remain lowercased, but I'm not 100% sure.

``` Anoited Son of God,``` 
 this should be Anointed Son of God right? just making sure its a typo.

**Comment by waytohealthfoundation** [comment]
All He/His should be capitalized when you’re referring to Jesus.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Iconians** [comment]
thanks for asking Rahnken and making sure, as the client answered the question, I will say they are the authority as to how they want their copy
