### ISSUE TITLE
OUR TEAM/PUBLIC DOCUMENTS and suggestions for design changes (aboutPage)

### ISSUE THREAD

**Issue by Iconians** [waytohealthfoundation/release-2024#34]
OUR TEAM 
"Meet our evergrowing team of volunteers and missionaries. 
(More to come)"
Teah, Tina, Sharon, Fedelin, Verdiu, Wilson

PUBLIC DOCUMENTS
Financials and meeting minutes
How do we do this? Do I need to provide you with all the files to add?

**Comment by Coderuff919** [comment]
Hi @Iconians, 
- For our team what info will be there?
Picture, name, job title, descriptions about the person.
- For public documents, are this will be hosted somewhere, like Google drive or on the asset folder?

I will layout this on Figma to give you some idea before we code this.

**Comment by Iconians** [comment]
Hi Monica

I would imagine there will be pictures, job titles, and descriptions, it looks like there are some names provided right now but since the clients haven't provided us those details yet I would assume that would be the case and we can always change something, 

for the public docs at the bottom of the homepage there is a formsDownloadingDialog we can probably move that over to this page under public doc and it looks like all pdf are in the assets folder from the href I see on a tags, thank you for your help

**Comment by Coderuff919** [comment]
OK sounds good, I'll see what I can come up with on the design layout

**Comment by Coderuff919** [comment]
Hi Clayton, 
Please review my feedback and also suggestions on the Our Team & Public Documents layout, let me know if this is good to go and I can add the HTML/ CSS to the file.
[About Page Feedback.pdf](https://github.com/waytohealthfoundation/release-2024/files/13815674/About.Page.Feedback.pdf)
