### ISSUE TITLE
navbar updates (homepage)

### ISSUE THREAD

**Issue by Iconians** [waytohealthfoundation/release-2024#38]
1. make logo/brand name font size bigger
2. space out the navbar evenly 

![Image](https://github.com/waytohealthfoundation/release-2024/assets/95727830/29ba1c45-f94c-4118-976e-8e97b189d553)

**Comment by Rahnken** [comment]
Do you still want the space between the nav-logo and nav links , or did you want to distribute all that whitespace for the navlinks?

Additionally currently the logo is just a constructed H2 with a span, did we want to make an svg to improve reuseability of the logo in other places and uses or leave it as the text?
