### ISSUE TITLE
update carousel arrows(homepage)

### ISSUE THREAD

**Issue by Iconians** [waytohealthfoundation/release-2024#40]
make the arrows bigger

**Comment by mbndvmDevslopes** [comment]
Good morning Clayton.  I am a bit confused, as the carousel section seems to be devoid of content. hence there are no arrows to modify.  Maybe I am missing something??

  <section class="videos-carousel-wrapper" id="videos-carousel-wrapper">
      <div class="videos-carousel">

      </div>

    </section>

**Comment by Iconians** [comment]
if you look in the js files buildCarousel.js and carousel.js you will see Tyson built the Carousel using JavaScript so to find the class names for the css you'll need to look in those js files, hopefully this all makes sense

**Comment by mbndvmDevslopes** [comment]
Where can I find the shape and size of the original buttons in order to make them bigger?

**Comment by Iconians** [comment]
ok if you look at the buildCarousel.js you will see on lines 72-78 the buttons are being made and on lines 73 and 77 a classList is being added to the buttons so if you look for that class in the styles.css you can make the changes there which corresponds to lines 514-539 as there are a few different classes connected to those buttons if you can start up live server and search through the HTML in the dev tools and play around with styling it there then apply the final styles in the file

**Comment by mbndvmDevslopes** [comment]
got it.  Thanks.  Sorry for missing that.
