### ISSUE TITLE
upcoming events section(homepage)

### ISSUE THREAD

**Issue by Iconians** [waytohealthfoundation/release-2024#43]
1. thicker font weight and bigger font size
2. make this as a 2 column

![Image](https://github.com/waytohealthfoundation/release-2024/assets/95727830/4db67754-6b96-43d4-af43-2fc13a875c1a)

 paragraph

**Comment by Rahnken** [comment]
Did we want to increase the font weight and size of the whole homepage? or just this section.

**Comment by Iconians** [comment]
Monica mentioned it just for this section, thank you for asking though

**Comment by Rahnken** [comment]
I'm going to wait for #54 to be merged, there are some style changes in that PR that will conflict with my changes

**Comment by Iconians** [comment]
ok just merged it, sorry it took a couple days to get to this

**Comment by Rahnken** [comment]
Want to make sure, is the one column upcoming events header class, and the other the scripture like the first picture I've attached to this comment , or did you want just the header text to be split into 2 columns like the second picture? 
![image1](https://github.com/waytohealthfoundation/release-2024/assets/18472770/432bd86d-3c67-4577-86a6-821d8cf8a6db)
![image2](https://github.com/waytohealthfoundation/release-2024/assets/18472770/d9b085b4-52a6-4961-a9f4-3ed13c86c06f)

**Comment by Iconians** [comment]
from what I can tell from Monica's design it would be the 2nd picture you posted, she had some other suggestions for the scripture block, thanks for double-checking
