### ISSUE TITLE
navbar (about page)

### ISSUE THREAD

**Issue by Iconians** [waytohealthfoundation/release-2024#56]
![Image](https://github.com/waytohealthfoundation/release-2024/assets/95727830/37173feb-aa35-402b-8bab-53b4badb9b90)

1. make logo text bigger check the homepage CSS for the pixels since we want it the same across the site, we might see if we can make the navbar have the same classes as the home page 

2. even spaces on each navbar

**Comment by Rahnken** [comment]
should I update the nav for all the pages, I just have to add a few classes to each one

**Comment by Iconians** [comment]
yes the navbar should look the same on each page, check the homepage navbar out as that might help with the logo size, and see if some other styles are being applied that can help with this task, thank you for asking questions and doing a great job

**Comment by Rahnken** [comment]
sorry I mean , should I add the same code to each page for this issue, or do you want me to wait and only do it when it we set up the new issues

**Comment by Iconians** [comment]
yes go ahead and add the code to the additional pages so they all have the same navbar, sorry I wasn't as clear as I should have been, thank you for checking though
