### ISSUE TITLE
fix text (about page)

### ISSUE THREAD

**Issue by Iconians** [waytohealthfoundation/release-2024#57]
1. make headers text bigger

2. make the font all the same as on home page 

note: don't touch vision and values as those are part of another issue 

![Image](https://github.com/waytohealthfoundation/release-2024/assets/95727830/935e8996-9edf-462d-91e8-8b67871dc6e5)

**Comment by Coderuff919** [comment]
Hi @Iconians , I am only changing the Who We Are section, leaving out the Who We Are (since Vision & Value) are part of this section) and Board Member section (there is a pull request on this) - I see those are part of other issues. Let me know if that is not the case.
Thanks.

**Comment by Iconians** [comment]
Hi, @Coderuff919 I finished reviewing the other PRs and merged them that would have affected your task here so you can change the font text and headings to what you suggested. Eric is working on the navbar but the rest of the page is yours to fix, you should see the updated differences if you do the git pull, thank you for checking and helping prevent merge conflicts

**Comment by Coderuff919** [comment]
OK will do. I will fix all of that. Thanks @Iconians

**Comment by Coderuff919** [comment]
Are you going to create a different issue to fix the board members section, since this branch is closed?
