### ISSUE TITLE
add Donations, needed supplies, mission trips sections

### ISSUE THREAD

**Issue by Iconians** [waytohealthfoundation/release-2024#72]
make donations section like below (these sections don't have much or any content, just getting them on the page)
put these at the top of the page

DONATIONS 

Paypal Link
Venmo: @Cite-Soleil

make needed supplies section 

NEEDED SUPPLIES

TBD

make Mission trips section 

MISSION TRIPS DATAPAGE

TBD

**Comment by mbndvmDevslopes** [comment]
Sorry to bother with a question, but on  which page should I place this?  How to help?  Sorry if I missed it..Matt

**Comment by Iconians** [comment]
oh no problem, I must of forgot to put on it on the issues title, but this goes on the top of the how to help page, you'll see the outline in the discord chat, thanks again for being willing to help
