### ISSUE TITLE
design newsletters page, Gallery Page

### ISSUE THREAD

**Issue by Iconians** [waytohealthfoundation/release-2024#73]
Here is the info for the newsletter page 

I have newsletters I have sent out in the past. How do you want these sent to you? 

Sign up for our newsletter: way to enter in their email address 

Gallery page 

no info has been provided yet but I am thinking of a slideshow and below a place where they can click on the individual images you the expert in design

reach out for any questions

**Comment by Coderuff919** [comment]
Hi @Iconians, is the Newsletter page and Gallery Pages will be 2 separate pages or everything in one page?

**Comment by Iconians** [comment]
how they have it in the outline it's 2 pages but we really don't have much info on either of them, I gave you the info that they gave us for the newsletter page but there was really no content information other then asking how Tyson would like to receive the photos for the gallery page, use your best judgement in designing these pages, thank you

**Comment by Coderuff919** [comment]
OK thanks for clarifying, I'll come up with something and you can give me feedback, and go from there.

**Comment by Iconians** [comment]
sounds good thank you

**Comment by Coderuff919** [comment]
Do we have a sample of their newsletter by any chance? I just want to get an ideas what the content will be.

**Comment by Iconians** [comment]
I don't believe so I gave you the only info that was on the outline for that page

**Comment by Iconians** [comment]
this is the only other info we were given 

Newsletter 

 Description
  Serving the Poor
  Reflection & Thought
  Cholera in Haiti Report 
  Sign up for our newsletter

**Comment by Coderuff919** [comment]
OK, I'll see what I can do from that info. Thanks Clayton!

**Comment by Coderuff919** [comment]
[Newsletter.pdf](https://github.com/waytohealthfoundation/release-2024/files/14136108/Newsletter.pdf)
Hi Clayton, 
Please review the Newsletter and Gallery layout. 
Thanks.

**Comment by Coderuff919** [comment]
Here is the Gallery layout
![Gallery](https://github.com/waytohealthfoundation/release-2024/assets/29670163/4df15bb6-1a46-4efc-acf1-c58a6a14c951)
