### ISSUE TITLE
upcoming/current events - yellow

### ISSUE THREAD

**Issue by Iconians** [waytohealthfoundation/release-2024#8]
this section will go under the intro text section 

copy from client

Upcoming Events
--
Giving Tuesday, November 28, 2023
Participate in Giving Tuesday by supporting Way to Health, enabling us to sustain crucial care for the underprivileged. A mere $1 can furnish medicine for a malnourished baby, potentially saving their life. Your contribution makes a significant impact on those in need.
 
Expansion of the Malnourished Baby Feeding Initiative
As we conclude 2023, unite with us to broaden our feeding initiative. We aim to extend the feeding program from 34 malnourished babies to 90, reaching more communities by expanding into additional neighborhoods in Cite Soleil, Haiti. (Add in a LEARN MORE link that goes into the "Our Work" datapage)

**Comment by mbndvmDevslopes** [comment]
Thanks.  Is the intro text section 'who we are?'.  I cannot seem to locate a section that is titled intro text.  Thanks

**Comment by Iconians** [comment]
sorry for not being more clear the intro text section is a new section that Zach is working on which is going underneath the youtube video that Monica is working on you can check the outline that was posted a couple of days ago to get a better grasp of how the new site is structured as its a bit different from how it is currently

**Comment by mbndvmDevslopes** [comment]
No worries, got it.  I will just add the section.  I assume the format design is also there?  I'll take a look.  It shouldn't take too long to add a section with a header...

**Comment by Iconians** [comment]
sounds good might be a good idea to perform a git pull as the other developer have finished their sections and things may  be a bit clearer

**Comment by mbndvmDevslopes** [comment]
Hey, I am going to have to bow out.  I don't understand what I am supposed to do and fear I won't be able to accomplish it.  Sorry and thanks.
